// AUTO-GENERATED by script: maps public/photo paths to dimensions
export const PHOTO_SIZES: Record<string, {width:number; height:number}> = {
  "/photos/og-pricing.webp": {
    "width": 1200,
    "height": 800
  },
  "/photos/og-ai-automation.webp": {
    "width": 1200,
    "height": 800
  },
  "/photos/og-app-development.png": {
    "width": 1200,
    "height": 800
  },
  "/photos/fysal-headshot.png": {
    "width": 511,
    "height": 775
  },
  "/photos/og-ai-automation.png": {
    "width": 1200,
    "height": 800
  },
  "/photos/fysal-headshot.webp": {
    "width": 511,
    "height": 775
  },
  "/photos/og-custom-software.webp": {
    "width": 1200,
    "height": 800
  },
  "/photos/og-home.jpg": {
    "width": 1200,
    "height": 800
  },
  "/photos/nav-headshot.webp": {
    "width": 543,
    "height": 678
  },
  "/photos/3d-nutab-logo.png": {
    "width": 600,
    "height": 600
  },
  "/photos/og-custom-software.png": {
    "width": 1200,
    "height": 800
  },
  "/photos/nav-headshot.png": {
    "width": 543,
    "height": 678
  },
  "/photos/og-photo-media.webp": {
    "width": 1200,
    "height": 800
  },
  "/photos/og-brand-design.webp": {
    "width": 1200,
    "height": 800
  },
  "/photos/nutab-logo.webp": {
    "width": 1120,
    "height": 1080
  },
  "/photos/og-home.webp": {
    "width": 1200,
    "height": 800
  },
  "/photos/og-pricing.png": {
    "width": 1200,
    "height": 800
  },
  "/photos/og-photo-media.png": {
    "width": 1200,
    "height": 800
  },
  "/photos/og-app-development.webp": {
    "width": 1200,
    "height": 800
  },
  "/photos/3d-nutab-logo.webp": {
    "width": 600,
    "height": 600
  },
  "/photos/og-brand-design.png": {
    "width": 1200,
    "height": 800
  },
  "/photos/nutab-logo.png": {
    "width": 1120,
    "height": 1080
  }
};
